global:
  error-sound: "ENTITY_VILLAGER_NO"

spawn:
  teleport-delay-seconds: 5
  cooldown-seconds: 10
  teleporting-sound: "BLOCK_NOTE_BLOCK_PLING"
  default-spawn: "1"

invsee:
  title: "&7InvSee: &#38c1fc%target%"