global:
  error-sound: "ENTITY.VILLAGER.NO"

spawn:
  teleport-delay-seconds: 5
  cooldown-seconds: 10
  teleporting-sound: "BLOCK.NOTE_BLOCK.PLING"
  default-spawn: "1"

invsee:
  title: "&fInvSee: &#38c1fc%target%"

broadcast:
  sound: "BLOCK.NOTE_BLOCK.BELL"

discord:
  sound: "BLOCK.NOTE_BLOCK.PLING"
  lines:
    -  "&#38c1fcᴊᴏɪɴ ᴛʜᴇ Example ᴄᴏᴍᴍᴜɴɪᴛʏ"
    -  "&#38c1fc&l•&r &f&ndiscord.gg/yourserver"

live:
  cooldown-minutes: 15
  sound: "BLOCK.NOTE_BLOCK.BELL"
  lines:
    - ""
    - "  &#38c1fc&l%player% is now live!"
    - ""
    - "  &7Watch the stream:"
    - "  &f%link%"
    - ""

death:
  # Leave empty to disable
  prefix: "&#ff0000☠ "
  message-color: "&#ff0000"
  suffix: "&#ff0000."