global:
  error-sound: "ENTITY.VILLAGER.NO"

spawn:
  teleport-delay-seconds: 5
  cooldown-seconds: 10
  teleporting-sound: "BLOCK.NOTE_BLOCK.PLING"
  default-spawn: "1"

invsee:
  title: "&fInvSee: &#38c1fc%target%"

broadcast:
  sound: "BLOCK.NOTE_BLOCK.BELL"